import type { Metadata } from 'next'
import './globals.css'
import Footer from '@/components/layouts/Footer'
import Navigation from '@/components/layouts/Navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
