'use client'

import BackButton from '@/components/ui/BackButton'
import EmblaCarousel from '@/components/ui/EmblaCarousel'
import TiptapViewer from '@/components/ui/TiptapViewer'
//  json {
//  title : 'Create Next App' ,
//      thumbnail : 'iamge/thumbnail.png' ,
//      images : [ { id : 1 , image : '/thumb1.jpeg' , title : '첫 번째 슬라이드' } , { id : 2 , image : '/thumb1.jpeg' , title : '2 번째 슬라이드' } , { id : 3 , image : '/thumb3.jpeg' , title : '3 번째 슬라이드' } , { id : 4 , image : '/thumb4.jpeg' , title : '4 번째 슬라이드' } ]
//          description : 'Generated by create next app' ,
// }
import { useParams, usePathname, useRouter } from 'next/navigation'
import React from 'react'

const dummyData = {
  id: 1,
  title: '모던한 웹 포트폴리오 디자인',
  thumbnail: '/images/portfolio1.jpg',
  images: [
    {
      id: 1,
      image: '/thumb1.jpeg',
      title: '첫 번째 슬라이드',
    },
    {
      id: 2,
      image: '/thumb1.jpeg',
      title: '2 번째 슬라이드',
    },
    {
      id: 3,
      image: '/thumb3.jpeg',
      title: '3 번째 슬라이드',
    },
    {
      id: 4,
      image: '/thumb4.jpeg',
      title: '4 번째 슬라이드',
    },
  ],
  description:
    '##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자 ##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.인과 부드러운 애니메이션을 적용했습니다. ##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다. ##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다. ##Next.js와  <h>Tailwind CSS</h>를 활용한 현대적인 포트폴리오 웹사이트입니다. 반응형 디자인과 부드러운 애니메이션을 적용했습니다.',
}
const PostDeatail = () => {
  // const pathname = usePathname()
  const router = useRouter()
  const params = useParams()

  const handleEdit = () => {
    router.push(`/post/${params.id}/edit`)
  }
  return (
    <>
      <div className="flex items-center justify-between p-4">
        <BackButton location="post" id={params.id} />
      </div>
      <div className="laptop:items-center mx-auto my-0 flex min-h-screen w-4/5 items-start justify-center  gap-6 p-4">
        <div className="mx-auto flex max-w-4xl flex-col gap-6">
          {/* 캐러셀 섹션 */}
          <section className="w-full">
            <EmblaCarousel slides={dummyData.images} />
          </section>
        </div>
      </div>
      {/* 콘텐츠 섹션 */}
      <section className="w-full p-4">
        <h2 className="mt-4 text-2xl font-bold">
          {dummyData.title} {dummyData.images.length}
        </h2>
        <div className="mx-auto my-0 w-4/5">
          <TiptapViewer content={dummyData.description} />
        </div>
      </section>
    </>
  )
}

export default PostDeatail
